name: playground
description: A playground to test various use cases with the wolt modal sheet with imperative navigation
publish_to: "none"
version: 1.0.0

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: '>=3.7.2'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  wolt_modal_sheet:
    path: ..
  wolt_responsive_layout_grid: ^0.0.3
  demo_ui_components:
    path: ../demo_ui_components
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.18.2
  patrol: ^3.5.0
  patrol_finders: ^2.0.1+1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/

patrol: 
  android:
    package_name: com.wolt_modal_sheet.playground.playground
  ios:
    bundle_id: com.woltmodalsheet.playground.playground
  macos:
    bundle_id: pl.leancode.patrol.macos.example